#include "FSMC_SRAM_s.h"

void FSMC_Init_s(void)
{
    // 开启FSMC以及复用的GPIO时钟
    RCC->AHB3ENR |= RCC_AHB3ENR_FSMCEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;

    // 地址线复用
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 0;
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 4;
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 8;
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 12;
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 16;
    GPIOF->AFR[0] |= GPIO_AF_FSMC << 20;
    GPIOF->AFR[1] |= GPIO_AF_FSMC << 16;
    GPIOF->AFR[1] |= GPIO_AF_FSMC << 20;
    GPIOF->AFR[1] |= GPIO_AF_FSMC << 24;
    GPIOF->AFR[1] |= ((uint32_t)GPIO_AF_FSMC << 28);

    GPIOG->AFR[0] |= GPIO_AF_FSMC << 0;
    GPIOG->AFR[0] |= GPIO_AF_FSMC << 4;
    GPIOG->AFR[0] |= GPIO_AF_FSMC << 8;
    GPIOG->AFR[0] |= GPIO_AF_FSMC << 12;
    GPIOG->AFR[0] |= GPIO_AF_FSMC << 16;
    GPIOG->AFR[0] |= GPIO_AF_FSMC << 20;

    GPIOD->AFR[1] |= GPIO_AF_FSMC << 12;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 16;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 20;

    GPIOF->MODER |= GPIO_MODER_MODER0_1 | GPIO_MODER_MODER1_1 | GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1 | GPIO_MODER_MODER4_1 | GPIO_MODER_MODER5_1 | GPIO_MODER_MODER12_1 | GPIO_MODER_MODER13_1 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER15_1;
    GPIOF->MODER &= ~(GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0 | GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
    GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0 | GPIO_OSPEEDER_OSPEEDR1 | GPIO_OSPEEDER_OSPEEDR2 | GPIO_OSPEEDER_OSPEEDR3 | GPIO_OSPEEDER_OSPEEDR4 | GPIO_OSPEEDER_OSPEEDR5 | GPIO_OSPEEDER_OSPEEDR12 | GPIO_OSPEEDER_OSPEEDR13 | GPIO_OSPEEDER_OSPEEDR14 | GPIO_OSPEEDER_OSPEEDR15;
    GPIOF->PUPDR |= GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR3_0 | GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR5_0 | GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR13_0 | GPIO_PUPDR_PUPDR14_0 | GPIO_PUPDR_PUPDR15_0;

    GPIOG->MODER |= GPIO_MODER_MODER0_1 | GPIO_MODER_MODER1_1 | GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1 | GPIO_MODER_MODER4_1 | GPIO_MODER_MODER5_1;
    GPIOG->MODER &= ~(GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER2_0 | GPIO_MODER_MODER3_0 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0);
    GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0 | GPIO_OSPEEDER_OSPEEDR1 | GPIO_OSPEEDER_OSPEEDR2 | GPIO_OSPEEDER_OSPEEDR3 | GPIO_OSPEEDER_OSPEEDR4 | GPIO_OSPEEDER_OSPEEDR5;
    GPIOG->PUPDR |= GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR3_0 | GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR5_0;

    GPIOD->MODER |= GPIO_MODER_MODER11_1 | GPIO_MODER_MODER12_1 | GPIO_MODER_MODER13_1;
    GPIOD->MODER &= ~(GPIO_MODER_MODER11_0 | GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0);
    GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11 | GPIO_OSPEEDER_OSPEEDR12 | GPIO_OSPEEDER_OSPEEDR13;
    GPIOD->PUPDR |= GPIO_PUPDR_PUPDR11_0 | GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR13_0;

    // 数据线复用
    GPIOD->AFR[0] |= GPIO_AF_FSMC << 0;
    GPIOD->AFR[0] |= GPIO_AF_FSMC << 4;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 0;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 4;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 8;
    GPIOD->AFR[1] |= GPIO_AF_FSMC << 24;
    GPIOD->AFR[1] |= ((uint32_t)GPIO_AF_FSMC << 28);

    GPIOE->AFR[0] |= ((uint32_t)GPIO_AF_FSMC << 28);
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 0;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 4;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 8;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 12;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 16;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 20;
    GPIOE->AFR[1] |= GPIO_AF_FSMC << 24;
    GPIOE->AFR[1] |= ((uint32_t)GPIO_AF_FSMC << 28);

    GPIOD->MODER |= GPIO_MODER_MODER0_1 | GPIO_MODER_MODER1_1 | GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER15_1;
    GPIOD->MODER &= ~(GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0 | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0 | GPIO_MODER_MODER10_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
    GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0 | GPIO_OSPEEDER_OSPEEDR1 | GPIO_OSPEEDER_OSPEEDR8 | GPIO_OSPEEDER_OSPEEDR9 | GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR14 | GPIO_OSPEEDER_OSPEEDR15;
    GPIOD->PUPDR |= GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR8_0 | GPIO_PUPDR_PUPDR9_0 | GPIO_PUPDR_PUPDR10_0 | GPIO_PUPDR_PUPDR14_0 | GPIO_PUPDR_PUPDR15_0;

    GPIOE->MODER |= GPIO_MODER_MODER7_1 | GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1 | GPIO_MODER_MODER12_1 | GPIO_MODER_MODER13_1 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER15_1;
    GPIOE->MODER &= ~(GPIO_MODER_MODER7_0 | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0 | GPIO_MODER_MODER10_0 | GPIO_MODER_MODER11_0 | GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
    GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7 | GPIO_OSPEEDER_OSPEEDR8 | GPIO_OSPEEDER_OSPEEDR9 | GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR11 | GPIO_OSPEEDER_OSPEEDR12 | GPIO_OSPEEDER_OSPEEDR13 | GPIO_OSPEEDER_OSPEEDR14 | GPIO_OSPEEDER_OSPEEDR15;
    GPIOE->PUPDR |= GPIO_PUPDR_PUPDR7_0 | GPIO_PUPDR_PUPDR8_0 | GPIO_PUPDR_PUPDR9_0 | GPIO_PUPDR_PUPDR10_0 | GPIO_PUPDR_PUPDR11_0 | GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR13_0 | GPIO_PUPDR_PUPDR14_0 | GPIO_PUPDR_PUPDR15_0;

    // 功能线复用，UB，LB，OE，WE，CE
    GPIOE->AFR[0] |= GPIO_AF_FSMC << 4;
    GPIOE->AFR[0] |= GPIO_AF_FSMC << 0;
    GPIOD->AFR[0] |= GPIO_AF_FSMC << 16;
    GPIOD->AFR[0] |= GPIO_AF_FSMC << 20;
    GPIOG->AFR[1] |= GPIO_AF_FSMC << 8;

    GPIOE->MODER |= GPIO_MODER_MODER0_1 | GPIO_MODER_MODER1_1;
    GPIOE->MODER &= ~(GPIO_MODER_MODER0_0 | GPIO_MODER_MODER1_0);
    GPIOE->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0 | GPIO_OSPEEDER_OSPEEDR1;
    GPIOE->PUPDR |= GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR1_0;

    GPIOD->MODER |= GPIO_MODER_MODER4_1 | GPIO_MODER_MODER5_1;
    GPIOD->MODER &= ~(GPIO_MODER_MODER4_0 | GPIO_MODER_MODER5_0);
    GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4 | GPIO_OSPEEDER_OSPEEDR5;
    GPIOD->PUPDR |= GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR5_0;

    GPIOG->MODER |= GPIO_MODER_MODER10_1;
    GPIOG->MODER &= ~GPIO_MODER_MODER10_0;
    GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10;
    GPIOG->PUPDR |= GPIO_PUPDR_PUPDR10_0;

    // 关闭地址总线和数据总线的复用功能
    FSMC_Bank1->BTCR[4] &= ~FSMC_BCR3_MUXEN;

    // 存储器类型选择SRAM
    FSMC_Bank1->BTCR[4] &= ~FSMC_BCR3_MTYP;

    // 总线宽度16
    FSMC_Bank1->BTCR[4] &= ~FSMC_BCR3_MWID_1;
    FSMC_Bank1->BTCR[4] |= FSMC_BCR3_MWID_0;

    // 禁用flash，这里是SRAM
    FSMC_Bank1->BTCR[4] &= ~FSMC_BCR3_FACCEN;

    // 启用写使能
    FSMC_Bank1->BTCR[4] |= FSMC_BCR3_WREN;

    // 禁用扩展模式
    FSMC_Bank1->BTCR[4] &= ~FSMC_BCR3_EXTMOD;

    // 时序设置
    // 建立地址时间0
    FSMC_Bank1->BTCR[5] &= ~FSMC_BTR3_ADDSET;

    // 数据保持时间
    FSMC_Bank1->BTCR[5] &= ~FSMC_BTR3_DATAST;
    FSMC_Bank1->BTCR[5] |= 24 << 8;

    // 使能FSMC
    FSMC_Bank1->BTCR[4] |= FSMC_BCR3_MBKEN;
}
