#include <stdint.h>
#include "stm32f4xx.h"

int main(void)
{
    RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
    GPIOF -> MODER |= GPIO_MODER_MODER9_0;
    GPIOF -> MODER &= ~GPIO_MODER_MODER9_1;
	  GPIOF -> MODER |= GPIO_MODER_MODER10_0;
    GPIOF -> MODER &= ~GPIO_MODER_MODER10_1;
    GPIOF -> OTYPER &= ~ (GPIO_OTYPER_OT_9 | GPIO_OTYPER_OT_10);
    GPIOF -> OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_0 | GPIO_OSPEEDER_OSPEEDR9_1 | GPIO_OSPEEDER_OSPEEDR10_0 | GPIO_OSPEEDER_OSPEEDR10_1;
    GPIOF -> PUPDR &= ~(GPIO_PUPDR_PUPDR9_1 | GPIO_PUPDR_PUPDR10_1);
    GPIOF -> PUPDR |= GPIO_PUPDR_PUPDR9_0 | GPIO_PUPDR_PUPDR10_0;
		GPIOF -> ODR |= GPIO_ODR_ODR_9 | GPIO_ODR_ODR_10;
		GPIOF -> ODR &= ~(GPIO_ODR_ODR_9 | GPIO_ODR_ODR_10);
    while(1)
    {}
}
